[package]
name = "rustend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.78"
aes-gcm = "0.10.1"
sha256 = "1.1.2"
getrandom = { version = "0.2", features = ["js"] }
