name: Build and Test React

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build Rustend
        run: |
          cd client
          npm run build:wasm
      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Build React
        run: |
          cd client
          npm run build:react
