name: Test Rustend Crypting

on: [push, pull_request]

jobs:
  test-crypting:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check formatting
      run: |
        cd rustend
        cargo fmt -- --check

    - name: Run tests
      run: |
        cd rustend
        cargo test