name: Build and Push ARM Docker Image

on:
  workflow_dispatch
  push:
    branches:
      - main

jobs:
  build-and-push:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/arm64 -t ghcr.io/paivola-student-innovation-lab/dailycrypt:arm . -f arm.Dockerfile
          docker push ghcr.io/paivola-student-innovation-lab/dailycrypt:arm
